#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="yasio1_taxiDb")]
	public partial class TaxiDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCar_model(Car_model instance);
    partial void UpdateCar_model(Car_model instance);
    partial void DeleteCar_model(Car_model instance);
    partial void InsertCourse_status(Course_status instance);
    partial void UpdateCourse_status(Course_status instance);
    partial void DeleteCourse_status(Course_status instance);
    partial void InsertDriver_status(Driver_status instance);
    partial void UpdateDriver_status(Driver_status instance);
    partial void DeleteDriver_status(Driver_status instance);
    partial void InsertEmployee_type(Employee_type instance);
    partial void UpdateEmployee_type(Employee_type instance);
    partial void DeleteEmployee_type(Employee_type instance);
    partial void InsertEmployee(Employee instance);
    partial void UpdateEmployee(Employee instance);
    partial void DeleteEmployee(Employee instance);
    partial void InsertCar_type(Car_type instance);
    partial void UpdateCar_type(Car_type instance);
    partial void DeleteCar_type(Car_type instance);
    partial void InsertTaxi(Taxi instance);
    partial void UpdateTaxi(Taxi instance);
    partial void DeleteTaxi(Taxi instance);
    partial void InsertCourse(Course instance);
    partial void UpdateCourse(Course instance);
    partial void DeleteCourse(Course instance);
    #endregion
		
		public TaxiDataClassesDataContext() : 
				base(global::DAL.Properties.Settings.Default.yasio1_taxiDbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TaxiDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TaxiDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TaxiDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TaxiDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Car_model> Car_models
		{
			get
			{
				return this.GetTable<Car_model>();
			}
		}
		
		public System.Data.Linq.Table<Course_status> Course_status
		{
			get
			{
				return this.GetTable<Course_status>();
			}
		}
		
		public System.Data.Linq.Table<Driver_status> Driver_status
		{
			get
			{
				return this.GetTable<Driver_status>();
			}
		}
		
		public System.Data.Linq.Table<Employee_type> Employee_types
		{
			get
			{
				return this.GetTable<Employee_type>();
			}
		}
		
		public System.Data.Linq.Table<Employee> Employees
		{
			get
			{
				return this.GetTable<Employee>();
			}
		}
		
		public System.Data.Linq.Table<Car_type> Car_types
		{
			get
			{
				return this.GetTable<Car_type>();
			}
		}
		
		public System.Data.Linq.Table<Taxi> Taxis
		{
			get
			{
				return this.GetTable<Taxi>();
			}
		}
		
		public System.Data.Linq.Table<CourseAccepedView> CourseAccepedViews
		{
			get
			{
				return this.GetTable<CourseAccepedView>();
			}
		}
		
		public System.Data.Linq.Table<CourseInProgressView> CourseInProgressViews
		{
			get
			{
				return this.GetTable<CourseInProgressView>();
			}
		}
		
		public System.Data.Linq.Table<CourseView> CourseViews
		{
			get
			{
				return this.GetTable<CourseView>();
			}
		}
		
		public System.Data.Linq.Table<EmployeeView> EmployeeViews
		{
			get
			{
				return this.GetTable<EmployeeView>();
			}
		}
		
		public System.Data.Linq.Table<TaxiDriverView> TaxiDriverViews
		{
			get
			{
				return this.GetTable<TaxiDriverView>();
			}
		}
		
		public System.Data.Linq.Table<Course> Courses
		{
			get
			{
				return this.GetTable<Course>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Car_model")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Car_model : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _producer;
		
		private string _model;
		
		private System.Nullable<int> _production_year;
		
		private int _seats;
		
		private EntitySet<Taxi> _Taxis;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnproducerChanging(string value);
    partial void OnproducerChanged();
    partial void OnmodelChanging(string value);
    partial void OnmodelChanged();
    partial void Onproduction_yearChanging(System.Nullable<int> value);
    partial void Onproduction_yearChanged();
    partial void OnseatsChanging(int value);
    partial void OnseatsChanged();
    #endregion
		
		public Car_model()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producer", DbType="VarChar(150)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string producer
		{
			get
			{
				return this._producer;
			}
			set
			{
				if ((this._producer != value))
				{
					this.OnproducerChanging(value);
					this.SendPropertyChanging();
					this._producer = value;
					this.SendPropertyChanged("producer");
					this.OnproducerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="VarChar(150)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string model
		{
			get
			{
				return this._model;
			}
			set
			{
				if ((this._model != value))
				{
					this.OnmodelChanging(value);
					this.SendPropertyChanging();
					this._model = value;
					this.SendPropertyChanged("model");
					this.OnmodelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_production_year", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.Nullable<int> production_year
		{
			get
			{
				return this._production_year;
			}
			set
			{
				if ((this._production_year != value))
				{
					this.Onproduction_yearChanging(value);
					this.SendPropertyChanging();
					this._production_year = value;
					this.SendPropertyChanged("production_year");
					this.Onproduction_yearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seats", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public int seats
		{
			get
			{
				return this._seats;
			}
			set
			{
				if ((this._seats != value))
				{
					this.OnseatsChanging(value);
					this.SendPropertyChanging();
					this._seats = value;
					this.SendPropertyChanged("seats");
					this.OnseatsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Car_model_Taxi", Storage="_Taxis", ThisKey="id", OtherKey="car_model_id")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6, EmitDefaultValue=false)]
		public EntitySet<Taxi> Taxis
		{
			get
			{
				if ((this.serializing 
							&& (this._Taxis.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Taxis;
			}
			set
			{
				this._Taxis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Taxis(Taxi entity)
		{
			this.SendPropertyChanging();
			entity.Car_model = this;
		}
		
		private void detach_Taxis(Taxi entity)
		{
			this.SendPropertyChanging();
			entity.Car_model = null;
		}
		
		private void Initialize()
		{
			this._Taxis = new EntitySet<Taxi>(new Action<Taxi>(this.attach_Taxis), new Action<Taxi>(this.detach_Taxis));
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Course_status")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Course_status : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private EntitySet<Course> _Courses;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public Course_status()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Course_status_Course", Storage="_Courses", ThisKey="id", OtherKey="course_status_id")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3, EmitDefaultValue=false)]
		public EntitySet<Course> Courses
		{
			get
			{
				if ((this.serializing 
							&& (this._Courses.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Courses;
			}
			set
			{
				this._Courses.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Courses(Course entity)
		{
			this.SendPropertyChanging();
			entity.Course_status = this;
		}
		
		private void detach_Courses(Course entity)
		{
			this.SendPropertyChanging();
			entity.Course_status = null;
		}
		
		private void Initialize()
		{
			this._Courses = new EntitySet<Course>(new Action<Course>(this.attach_Courses), new Action<Course>(this.detach_Courses));
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Driver_status")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Driver_status : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private EntitySet<TaxiDriver> _TaxiDrivers;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public Driver_status()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Driver_status_TaxiDriver", Storage="_TaxiDrivers", ThisKey="id", OtherKey="driver_status_id")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3, EmitDefaultValue=false)]
		public EntitySet<TaxiDriver> TaxiDrivers
		{
			get
			{
				if ((this.serializing 
							&& (this._TaxiDrivers.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._TaxiDrivers;
			}
			set
			{
				this._TaxiDrivers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaxiDrivers(TaxiDriver entity)
		{
			this.SendPropertyChanging();
			entity.Driver_status = this;
		}
		
		private void detach_TaxiDrivers(TaxiDriver entity)
		{
			this.SendPropertyChanging();
			entity.Driver_status = null;
		}
		
		private void Initialize()
		{
			this._TaxiDrivers = new EntitySet<TaxiDriver>(new Action<TaxiDriver>(this.attach_TaxiDrivers), new Action<TaxiDriver>(this.detach_TaxiDrivers));
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employee_type")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Employee_type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private EntitySet<Employee> _Employees;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public Employee_type()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employee_type_Employee", Storage="_Employees", ThisKey="id", OtherKey="employee_type_id")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3, EmitDefaultValue=false)]
		public EntitySet<Employee> Employees
		{
			get
			{
				if ((this.serializing 
							&& (this._Employees.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Employees;
			}
			set
			{
				this._Employees.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Employees(Employee entity)
		{
			this.SendPropertyChanging();
			entity.Employee_type = this;
		}
		
		private void detach_Employees(Employee entity)
		{
			this.SendPropertyChanging();
			entity.Employee_type = null;
		}
		
		private void Initialize()
		{
			this._Employees = new EntitySet<Employee>(new Action<Employee>(this.attach_Employees), new Action<Employee>(this.detach_Employees));
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employee")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	[global::System.Data.Linq.Mapping.InheritanceMappingAttribute(Code="0", Type=typeof(Employee), IsDefault=true)]
	[global::System.Data.Linq.Mapping.InheritanceMappingAttribute(Code="2", Type=typeof(Dispatcher))]
	[global::System.Data.Linq.Mapping.InheritanceMappingAttribute(Code="1", Type=typeof(TaxiDriver))]
	[global::System.Data.Linq.Mapping.InheritanceMappingAttribute(Code="3", Type=typeof(Admin))]
	[global::System.Runtime.Serialization.KnownTypeAttribute(typeof(Dispatcher))]
	[global::System.Runtime.Serialization.KnownTypeAttribute(typeof(TaxiDriver))]
	[global::System.Runtime.Serialization.KnownTypeAttribute(typeof(Admin))]
	public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _surname;
		
		private string _pesel;
		
		private string _house_nr;
		
		private string _postal_code;
		
		private string _city;
		
		private string _e_mail;
		
		private int _employee_type_id;
		
		private string _login;
		
		private string _password;
		
		private string _salt;
		
		private string _telephone;
		
		private string _street;
		
		private EntitySet<Course> _Courses;
		
		private EntitySet<Course> _Courses1;
		
		private EntityRef<Employee_type> _Employee_type;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnsurnameChanging(string value);
    partial void OnsurnameChanged();
    partial void OnpeselChanging(string value);
    partial void OnpeselChanged();
    partial void Onhouse_nrChanging(string value);
    partial void Onhouse_nrChanged();
    partial void Onpostal_codeChanging(string value);
    partial void Onpostal_codeChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void One_mailChanging(string value);
    partial void One_mailChanged();
    partial void Onemployee_type_idChanging(int value);
    partial void Onemployee_type_idChanged();
    partial void OnloginChanging(string value);
    partial void OnloginChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnsaltChanging(string value);
    partial void OnsaltChanged();
    partial void OntelephoneChanging(string value);
    partial void OntelephoneChanged();
    partial void OnstreetChanging(string value);
    partial void OnstreetChanged();
    #endregion
		
		public Employee()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_surname", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string surname
		{
			get
			{
				return this._surname;
			}
			set
			{
				if ((this._surname != value))
				{
					this.OnsurnameChanging(value);
					this.SendPropertyChanging();
					this._surname = value;
					this.SendPropertyChanged("surname");
					this.OnsurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pesel", DbType="char(11)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string pesel
		{
			get
			{
				return this._pesel;
			}
			set
			{
				if ((this._pesel != value))
				{
					this.OnpeselChanging(value);
					this.SendPropertyChanging();
					this._pesel = value;
					this.SendPropertyChanged("pesel");
					this.OnpeselChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_house_nr", DbType="VarChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string house_nr
		{
			get
			{
				return this._house_nr;
			}
			set
			{
				if ((this._house_nr != value))
				{
					this.Onhouse_nrChanging(value);
					this.SendPropertyChanging();
					this._house_nr = value;
					this.SendPropertyChanged("house_nr");
					this.Onhouse_nrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postal_code", DbType="VarChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string postal_code
		{
			get
			{
				return this._postal_code;
			}
			set
			{
				if ((this._postal_code != value))
				{
					this.Onpostal_codeChanging(value);
					this.SendPropertyChanging();
					this._postal_code = value;
					this.SendPropertyChanged("postal_code");
					this.Onpostal_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_mail", DbType="VarChar(150)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string e_mail
		{
			get
			{
				return this._e_mail;
			}
			set
			{
				if ((this._e_mail != value))
				{
					this.One_mailChanging(value);
					this.SendPropertyChanging();
					this._e_mail = value;
					this.SendPropertyChanged("e_mail");
					this.One_mailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_type_id", DbType="Int NOT NULL", IsDiscriminator=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public int employee_type_id
		{
			get
			{
				return this._employee_type_id;
			}
			set
			{
				if ((this._employee_type_id != value))
				{
					if (this._Employee_type.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onemployee_type_idChanging(value);
					this.SendPropertyChanging();
					this._employee_type_id = value;
					this.SendPropertyChanged("employee_type_id");
					this.Onemployee_type_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public string login
		{
			get
			{
				return this._login;
			}
			set
			{
				if ((this._login != value))
				{
					this.OnloginChanging(value);
					this.SendPropertyChanging();
					this._login = value;
					this.SendPropertyChanged("login");
					this.OnloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salt", DbType="Char(8)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public string salt
		{
			get
			{
				return this._salt;
			}
			set
			{
				if ((this._salt != value))
				{
					this.OnsaltChanging(value);
					this.SendPropertyChanging();
					this._salt = value;
					this.SendPropertyChanged("salt");
					this.OnsaltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="VarChar(20)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public string telephone
		{
			get
			{
				return this._telephone;
			}
			set
			{
				if ((this._telephone != value))
				{
					this.OntelephoneChanging(value);
					this.SendPropertyChanging();
					this._telephone = value;
					this.SendPropertyChanged("telephone");
					this.OntelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_street", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public string street
		{
			get
			{
				return this._street;
			}
			set
			{
				if ((this._street != value))
				{
					this.OnstreetChanging(value);
					this.SendPropertyChanging();
					this._street = value;
					this.SendPropertyChanged("street");
					this.OnstreetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employee_Course", Storage="_Courses", ThisKey="id", OtherKey="depositor_id")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15, EmitDefaultValue=false)]
		public EntitySet<Course> Courses
		{
			get
			{
				if ((this.serializing 
							&& (this._Courses.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Courses;
			}
			set
			{
				this._Courses.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employee_Course1", Storage="_Courses1", ThisKey="id", OtherKey="taxidriver_id")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=16, EmitDefaultValue=false)]
		public EntitySet<Course> Courses1
		{
			get
			{
				if ((this.serializing 
							&& (this._Courses1.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Courses1;
			}
			set
			{
				this._Courses1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employee_type_Employee", Storage="_Employee_type", ThisKey="employee_type_id", OtherKey="id", IsForeignKey=true)]
		public Employee_type Employee_type
		{
			get
			{
				return this._Employee_type.Entity;
			}
			set
			{
				Employee_type previousValue = this._Employee_type.Entity;
				if (((previousValue != value) 
							|| (this._Employee_type.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Employee_type.Entity = null;
						previousValue.Employees.Remove(this);
					}
					this._Employee_type.Entity = value;
					if ((value != null))
					{
						value.Employees.Add(this);
						this._employee_type_id = value.id;
					}
					else
					{
						this._employee_type_id = default(int);
					}
					this.SendPropertyChanged("Employee_type");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Courses(Course entity)
		{
			this.SendPropertyChanging();
			entity.Employee = this;
		}
		
		private void detach_Courses(Course entity)
		{
			this.SendPropertyChanging();
			entity.Employee = null;
		}
		
		private void attach_Courses1(Course entity)
		{
			this.SendPropertyChanging();
			entity.Employee1 = this;
		}
		
		private void detach_Courses1(Course entity)
		{
			this.SendPropertyChanging();
			entity.Employee1 = null;
		}
		
		private void Initialize()
		{
			this._Courses = new EntitySet<Course>(new Action<Course>(this.attach_Courses), new Action<Course>(this.detach_Courses));
			this._Courses1 = new EntitySet<Course>(new Action<Course>(this.attach_Courses1), new Action<Course>(this.detach_Courses1));
			this._Employee_type = default(EntityRef<Employee_type>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Dispatcher : Employee
	{
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    #endregion
		
		public Dispatcher()
		{
			this.Initialize();
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public new void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class TaxiDriver : Employee
	{
		
		private System.Nullable<int> _taxi_id;
		
		private string _position_name;
		
		private System.Nullable<decimal> _position_lon;
		
		private System.Nullable<int> _driver_status_id;
		
		private System.Nullable<decimal> _position_lat;
		
		private string _licence_number;
		
		private EntityRef<Driver_status> _Driver_status;
		
		private EntityRef<Taxi> _Taxi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontaxi_idChanging(System.Nullable<int> value);
    partial void Ontaxi_idChanged();
    partial void Onposition_nameChanging(string value);
    partial void Onposition_nameChanged();
    partial void Onposition_lonChanging(System.Nullable<decimal> value);
    partial void Onposition_lonChanged();
    partial void Ondriver_status_idChanging(System.Nullable<int> value);
    partial void Ondriver_status_idChanged();
    partial void Onposition_latChanging(System.Nullable<decimal> value);
    partial void Onposition_latChanged();
    partial void Onlicence_numberChanging(string value);
    partial void Onlicence_numberChanged();
    #endregion
		
		public TaxiDriver()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taxi_id", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public System.Nullable<int> taxi_id
		{
			get
			{
				return this._taxi_id;
			}
			set
			{
				if ((this._taxi_id != value))
				{
					if (this._Taxi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontaxi_idChanging(value);
					this.SendPropertyChanging();
					this._taxi_id = value;
					this.SendPropertyChanged("taxi_id");
					this.Ontaxi_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position_name", DbType="VarChar(150)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string position_name
		{
			get
			{
				return this._position_name;
			}
			set
			{
				if ((this._position_name != value))
				{
					this.Onposition_nameChanging(value);
					this.SendPropertyChanging();
					this._position_name = value;
					this.SendPropertyChanged("position_name");
					this.Onposition_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position_lon", DbType="Decimal(11,7)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<decimal> position_lon
		{
			get
			{
				return this._position_lon;
			}
			set
			{
				if ((this._position_lon != value))
				{
					this.Onposition_lonChanging(value);
					this.SendPropertyChanging();
					this._position_lon = value;
					this.SendPropertyChanged("position_lon");
					this.Onposition_lonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driver_status_id", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.Nullable<int> driver_status_id
		{
			get
			{
				return this._driver_status_id;
			}
			set
			{
				if ((this._driver_status_id != value))
				{
					if (this._Driver_status.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondriver_status_idChanging(value);
					this.SendPropertyChanging();
					this._driver_status_id = value;
					this.SendPropertyChanged("driver_status_id");
					this.Ondriver_status_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position_lat", DbType="Decimal(11,7)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<decimal> position_lat
		{
			get
			{
				return this._position_lat;
			}
			set
			{
				if ((this._position_lat != value))
				{
					this.Onposition_latChanging(value);
					this.SendPropertyChanging();
					this._position_lat = value;
					this.SendPropertyChanged("position_lat");
					this.Onposition_latChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_licence_number", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string licence_number
		{
			get
			{
				return this._licence_number;
			}
			set
			{
				if ((this._licence_number != value))
				{
					this.Onlicence_numberChanging(value);
					this.SendPropertyChanging();
					this._licence_number = value;
					this.SendPropertyChanged("licence_number");
					this.Onlicence_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Driver_status_TaxiDriver", Storage="_Driver_status", ThisKey="driver_status_id", OtherKey="id", IsForeignKey=true)]
		public Driver_status Driver_status
		{
			get
			{
				return this._Driver_status.Entity;
			}
			set
			{
				Driver_status previousValue = this._Driver_status.Entity;
				if (((previousValue != value) 
							|| (this._Driver_status.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Driver_status.Entity = null;
						previousValue.TaxiDrivers.Remove(this);
					}
					this._Driver_status.Entity = value;
					if ((value != null))
					{
						value.TaxiDrivers.Add(this);
						this._driver_status_id = value.id;
					}
					else
					{
						this._driver_status_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Driver_status");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Taxi_TaxiDriver", Storage="_Taxi", ThisKey="taxi_id", OtherKey="id", IsForeignKey=true)]
		public Taxi Taxi
		{
			get
			{
				return this._Taxi.Entity;
			}
			set
			{
				Taxi previousValue = this._Taxi.Entity;
				if (((previousValue != value) 
							|| (this._Taxi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Taxi.Entity = null;
						previousValue.TaxiDrivers.Remove(this);
					}
					this._Taxi.Entity = value;
					if ((value != null))
					{
						value.TaxiDrivers.Add(this);
						this._taxi_id = value.id;
					}
					else
					{
						this._taxi_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Taxi");
				}
			}
		}
		
		private void Initialize()
		{
			this._Driver_status = default(EntityRef<Driver_status>);
			this._Taxi = default(EntityRef<Taxi>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public new void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Admin : Employee
	{
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    #endregion
		
		public Admin()
		{
			this.Initialize();
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public new void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="yasio1_superuser.Car_type")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Car_type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _name;
		
		private int _id;
		
		private EntitySet<Taxi> _Taxis;
		
		private EntitySet<Course> _Courses;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
		
		public Car_type()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Car_type_Taxi", Storage="_Taxis", ThisKey="id", OtherKey="id_car_type")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3, EmitDefaultValue=false)]
		public EntitySet<Taxi> Taxis
		{
			get
			{
				if ((this.serializing 
							&& (this._Taxis.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Taxis;
			}
			set
			{
				this._Taxis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Car_type_Course", Storage="_Courses", ThisKey="id", OtherKey="car_type_id")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4, EmitDefaultValue=false)]
		public EntitySet<Course> Courses
		{
			get
			{
				if ((this.serializing 
							&& (this._Courses.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Courses;
			}
			set
			{
				this._Courses.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Taxis(Taxi entity)
		{
			this.SendPropertyChanging();
			entity.Car_type = this;
		}
		
		private void detach_Taxis(Taxi entity)
		{
			this.SendPropertyChanging();
			entity.Car_type = null;
		}
		
		private void attach_Courses(Course entity)
		{
			this.SendPropertyChanging();
			entity.Car_type = this;
		}
		
		private void detach_Courses(Course entity)
		{
			this.SendPropertyChanging();
			entity.Car_type = null;
		}
		
		private void Initialize()
		{
			this._Taxis = new EntitySet<Taxi>(new Action<Taxi>(this.attach_Taxis), new Action<Taxi>(this.detach_Taxis));
			this._Courses = new EntitySet<Course>(new Action<Course>(this.attach_Courses), new Action<Course>(this.detach_Courses));
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Taxi")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Taxi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _car_model_id;
		
		private string _registration_number;
		
		private string _taxi_number;
		
		private int _id_car_type;
		
		private EntitySet<TaxiDriver> _TaxiDrivers;
		
		private EntityRef<Car_model> _Car_model;
		
		private EntityRef<Car_type> _Car_type;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Oncar_model_idChanging(int value);
    partial void Oncar_model_idChanged();
    partial void Onregistration_numberChanging(string value);
    partial void Onregistration_numberChanged();
    partial void Ontaxi_numberChanging(string value);
    partial void Ontaxi_numberChanged();
    partial void Onid_car_typeChanging(int value);
    partial void Onid_car_typeChanged();
    #endregion
		
		public Taxi()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_model_id", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public int car_model_id
		{
			get
			{
				return this._car_model_id;
			}
			set
			{
				if ((this._car_model_id != value))
				{
					if (this._Car_model.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncar_model_idChanging(value);
					this.SendPropertyChanging();
					this._car_model_id = value;
					this.SendPropertyChanged("car_model_id");
					this.Oncar_model_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registration_number", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string registration_number
		{
			get
			{
				return this._registration_number;
			}
			set
			{
				if ((this._registration_number != value))
				{
					this.Onregistration_numberChanging(value);
					this.SendPropertyChanging();
					this._registration_number = value;
					this.SendPropertyChanged("registration_number");
					this.Onregistration_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taxi_number", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string taxi_number
		{
			get
			{
				return this._taxi_number;
			}
			set
			{
				if ((this._taxi_number != value))
				{
					this.Ontaxi_numberChanging(value);
					this.SendPropertyChanging();
					this._taxi_number = value;
					this.SendPropertyChanged("taxi_number");
					this.Ontaxi_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_car_type", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public int id_car_type
		{
			get
			{
				return this._id_car_type;
			}
			set
			{
				if ((this._id_car_type != value))
				{
					if (this._Car_type.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_car_typeChanging(value);
					this.SendPropertyChanging();
					this._id_car_type = value;
					this.SendPropertyChanged("id_car_type");
					this.Onid_car_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Taxi_TaxiDriver", Storage="_TaxiDrivers", ThisKey="id", OtherKey="taxi_id")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6, EmitDefaultValue=false)]
		public EntitySet<TaxiDriver> TaxiDrivers
		{
			get
			{
				if ((this.serializing 
							&& (this._TaxiDrivers.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._TaxiDrivers;
			}
			set
			{
				this._TaxiDrivers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Car_model_Taxi", Storage="_Car_model", ThisKey="car_model_id", OtherKey="id", IsForeignKey=true)]
		public Car_model Car_model
		{
			get
			{
				return this._Car_model.Entity;
			}
			set
			{
				Car_model previousValue = this._Car_model.Entity;
				if (((previousValue != value) 
							|| (this._Car_model.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Car_model.Entity = null;
						previousValue.Taxis.Remove(this);
					}
					this._Car_model.Entity = value;
					if ((value != null))
					{
						value.Taxis.Add(this);
						this._car_model_id = value.id;
					}
					else
					{
						this._car_model_id = default(int);
					}
					this.SendPropertyChanged("Car_model");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Car_type_Taxi", Storage="_Car_type", ThisKey="id_car_type", OtherKey="id", IsForeignKey=true)]
		public Car_type Car_type
		{
			get
			{
				return this._Car_type.Entity;
			}
			set
			{
				Car_type previousValue = this._Car_type.Entity;
				if (((previousValue != value) 
							|| (this._Car_type.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Car_type.Entity = null;
						previousValue.Taxis.Remove(this);
					}
					this._Car_type.Entity = value;
					if ((value != null))
					{
						value.Taxis.Add(this);
						this._id_car_type = value.id;
					}
					else
					{
						this._id_car_type = default(int);
					}
					this.SendPropertyChanged("Car_type");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaxiDrivers(TaxiDriver entity)
		{
			this.SendPropertyChanging();
			entity.Taxi = this;
		}
		
		private void detach_TaxiDrivers(TaxiDriver entity)
		{
			this.SendPropertyChanging();
			entity.Taxi = null;
		}
		
		private void Initialize()
		{
			this._TaxiDrivers = new EntitySet<TaxiDriver>(new Action<TaxiDriver>(this.attach_TaxiDrivers), new Action<TaxiDriver>(this.detach_TaxiDrivers));
			this._Car_model = default(EntityRef<Car_model>);
			this._Car_type = default(EntityRef<Car_type>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="yasio1_databaseUser.CourseAccepedView")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class CourseAccepedView
	{
		
		private System.Nullable<System.DateTime> _course_date;
		
		private string _client_name;
		
		private string _startpoint_name;
		
		private string _client_phone;
		
		private System.Nullable<int> _course_status_id;
		
		private string _dispatcher;
		
		private int _id;
		
		private int _dipatcher_id;
		
		public CourseAccepedView()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_date", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public System.Nullable<System.DateTime> course_date
		{
			get
			{
				return this._course_date;
			}
			set
			{
				if ((this._course_date != value))
				{
					this._course_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_name", DbType="VarChar(150)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string client_name
		{
			get
			{
				return this._client_name;
			}
			set
			{
				if ((this._client_name != value))
				{
					this._client_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startpoint_name", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string startpoint_name
		{
			get
			{
				return this._startpoint_name;
			}
			set
			{
				if ((this._startpoint_name != value))
				{
					this._startpoint_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_phone", DbType="VarChar(15)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string client_phone
		{
			get
			{
				return this._client_phone;
			}
			set
			{
				if ((this._client_phone != value))
				{
					this._client_phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_status_id", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<int> course_status_id
		{
			get
			{
				return this._course_status_id;
			}
			set
			{
				if ((this._course_status_id != value))
				{
					this._course_status_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dispatcher", DbType="VarChar(151) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string dispatcher
		{
			get
			{
				return this._dispatcher;
			}
			set
			{
				if ((this._dispatcher != value))
				{
					this._dispatcher = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dipatcher_id", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public int dipatcher_id
		{
			get
			{
				return this._dipatcher_id;
			}
			set
			{
				if ((this._dipatcher_id != value))
				{
					this._dipatcher_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="yasio1_databaseUser.CourseInProgressView")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class CourseInProgressView
	{
		
		private System.Nullable<System.DateTime> _course_date;
		
		private string _client_name;
		
		private string _startpoint_name;
		
		private string _client_phone;
		
		private System.Nullable<int> _course_status_id;
		
		private string _dispatcher;
		
		private string _driver;
		
		private int _id;
		
		private int _dispatcher_id;
		
		private int _driver_id;
		
		public CourseInProgressView()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_date", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public System.Nullable<System.DateTime> course_date
		{
			get
			{
				return this._course_date;
			}
			set
			{
				if ((this._course_date != value))
				{
					this._course_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_name", DbType="VarChar(150)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string client_name
		{
			get
			{
				return this._client_name;
			}
			set
			{
				if ((this._client_name != value))
				{
					this._client_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startpoint_name", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string startpoint_name
		{
			get
			{
				return this._startpoint_name;
			}
			set
			{
				if ((this._startpoint_name != value))
				{
					this._startpoint_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_phone", DbType="VarChar(15)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string client_phone
		{
			get
			{
				return this._client_phone;
			}
			set
			{
				if ((this._client_phone != value))
				{
					this._client_phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_status_id", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<int> course_status_id
		{
			get
			{
				return this._course_status_id;
			}
			set
			{
				if ((this._course_status_id != value))
				{
					this._course_status_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dispatcher", DbType="VarChar(151) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string dispatcher
		{
			get
			{
				return this._dispatcher;
			}
			set
			{
				if ((this._dispatcher != value))
				{
					this._dispatcher = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driver", DbType="VarChar(151) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string driver
		{
			get
			{
				return this._driver;
			}
			set
			{
				if ((this._driver != value))
				{
					this._driver = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dispatcher_id", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public int dispatcher_id
		{
			get
			{
				return this._dispatcher_id;
			}
			set
			{
				if ((this._dispatcher_id != value))
				{
					this._dispatcher_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driver_id", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public int driver_id
		{
			get
			{
				return this._driver_id;
			}
			set
			{
				if ((this._driver_id != value))
				{
					this._driver_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="yasio1_databaseUser.CourseView")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class CourseView
	{
		
		private System.Nullable<System.DateTime> _course_date;
		
		private string _client_name;
		
		private string _startpoint_name;
		
		private string _client_phone;
		
		private System.Nullable<int> _course_status_id;
		
		private string _dispatcher;
		
		private string _driver;
		
		private int _id;
		
		private int _dispatcher_id;
		
		private int _driver_id;
		
		public CourseView()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_date", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public System.Nullable<System.DateTime> course_date
		{
			get
			{
				return this._course_date;
			}
			set
			{
				if ((this._course_date != value))
				{
					this._course_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_name", DbType="VarChar(150)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string client_name
		{
			get
			{
				return this._client_name;
			}
			set
			{
				if ((this._client_name != value))
				{
					this._client_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startpoint_name", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string startpoint_name
		{
			get
			{
				return this._startpoint_name;
			}
			set
			{
				if ((this._startpoint_name != value))
				{
					this._startpoint_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_phone", DbType="VarChar(15)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string client_phone
		{
			get
			{
				return this._client_phone;
			}
			set
			{
				if ((this._client_phone != value))
				{
					this._client_phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_status_id", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<int> course_status_id
		{
			get
			{
				return this._course_status_id;
			}
			set
			{
				if ((this._course_status_id != value))
				{
					this._course_status_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dispatcher", DbType="VarChar(151) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string dispatcher
		{
			get
			{
				return this._dispatcher;
			}
			set
			{
				if ((this._dispatcher != value))
				{
					this._dispatcher = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driver", DbType="VarChar(151) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string driver
		{
			get
			{
				return this._driver;
			}
			set
			{
				if ((this._driver != value))
				{
					this._driver = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dispatcher_id", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public int dispatcher_id
		{
			get
			{
				return this._dispatcher_id;
			}
			set
			{
				if ((this._dispatcher_id != value))
				{
					this._dispatcher_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driver_id", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public int driver_id
		{
			get
			{
				return this._driver_id;
			}
			set
			{
				if ((this._driver_id != value))
				{
					this._driver_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="yasio1_databaseUser.EmployeeView")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class EmployeeView
	{
		
		private string _name;
		
		private string _surname;
		
		private string _pesel;
		
		private string _city;
		
		private string _house_nr;
		
		private string _postal_code;
		
		private string _street;
		
		private string _e_mail;
		
		private string _telephone;
		
		private string _employee_type;
		
		private int _id;
		
		private int _employee_type_id;
		
		public EmployeeView()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_surname", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string surname
		{
			get
			{
				return this._surname;
			}
			set
			{
				if ((this._surname != value))
				{
					this._surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pesel", DbType="Char(11)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string pesel
		{
			get
			{
				return this._pesel;
			}
			set
			{
				if ((this._pesel != value))
				{
					this._pesel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this._city = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_house_nr", DbType="VarChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string house_nr
		{
			get
			{
				return this._house_nr;
			}
			set
			{
				if ((this._house_nr != value))
				{
					this._house_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postal_code", DbType="VarChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string postal_code
		{
			get
			{
				return this._postal_code;
			}
			set
			{
				if ((this._postal_code != value))
				{
					this._postal_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_street", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string street
		{
			get
			{
				return this._street;
			}
			set
			{
				if ((this._street != value))
				{
					this._street = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_mail", DbType="VarChar(150)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string e_mail
		{
			get
			{
				return this._e_mail;
			}
			set
			{
				if ((this._e_mail != value))
				{
					this._e_mail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="VarChar(20)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public string telephone
		{
			get
			{
				return this._telephone;
			}
			set
			{
				if ((this._telephone != value))
				{
					this._telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public string employee_type
		{
			get
			{
				return this._employee_type;
			}
			set
			{
				if ((this._employee_type != value))
				{
					this._employee_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_type_id", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public int employee_type_id
		{
			get
			{
				return this._employee_type_id;
			}
			set
			{
				if ((this._employee_type_id != value))
				{
					this._employee_type_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="yasio1_databaseUser.TaxiDriverView")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class TaxiDriverView
	{
		
		private string _name;
		
		private string _surname;
		
		private string _telephone;
		
		private string _position_name;
		
		private string _taxi_number;
		
		private string _producer;
		
		private string _model;
		
		private string _car_type;
		
		private int _id;
		
		private int _taxi_id;
		
		private int _car_model_id;
		
		private int _car_type_id;
		
		private string _driver_status;
		
		public TaxiDriverView()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_surname", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string surname
		{
			get
			{
				return this._surname;
			}
			set
			{
				if ((this._surname != value))
				{
					this._surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="VarChar(20)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string telephone
		{
			get
			{
				return this._telephone;
			}
			set
			{
				if ((this._telephone != value))
				{
					this._telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position_name", DbType="VarChar(150)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string position_name
		{
			get
			{
				return this._position_name;
			}
			set
			{
				if ((this._position_name != value))
				{
					this._position_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taxi_number", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string taxi_number
		{
			get
			{
				return this._taxi_number;
			}
			set
			{
				if ((this._taxi_number != value))
				{
					this._taxi_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producer", DbType="VarChar(150)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string producer
		{
			get
			{
				return this._producer;
			}
			set
			{
				if ((this._producer != value))
				{
					this._producer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="VarChar(150)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string model
		{
			get
			{
				return this._model;
			}
			set
			{
				if ((this._model != value))
				{
					this._model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string car_type
		{
			get
			{
				return this._car_type;
			}
			set
			{
				if ((this._car_type != value))
				{
					this._car_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taxi_id", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public int taxi_id
		{
			get
			{
				return this._taxi_id;
			}
			set
			{
				if ((this._taxi_id != value))
				{
					this._taxi_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_model_id", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public int car_model_id
		{
			get
			{
				return this._car_model_id;
			}
			set
			{
				if ((this._car_model_id != value))
				{
					this._car_model_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_type_id", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public int car_type_id
		{
			get
			{
				return this._car_type_id;
			}
			set
			{
				if ((this._car_type_id != value))
				{
					this._car_type_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driver_status", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public string driver_status
		{
			get
			{
				return this._driver_status;
			}
			set
			{
				if ((this._driver_status != value))
				{
					this._driver_status = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Course")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Course : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _client_phone;
		
		private System.Nullable<int> _depositor_id;
		
		private System.Nullable<int> _taxidriver_id;
		
		private System.DateTime _date;
		
		private string _startpoint_name;
		
		private decimal _startpoint_lat;
		
		private decimal _startpoint_lon;
		
		private decimal _endpoint_lat;
		
		private decimal _endpoint_lon;
		
		private System.Nullable<int> _course_status_id;
		
		private System.Nullable<System.DateTime> _course_date;
		
		private string _client_name;
		
		private System.Nullable<int> _seats;
		
		private System.Nullable<int> _car_type_id;
		
		private EntityRef<Car_type> _Car_type;
		
		private EntityRef<Employee> _Employee;
		
		private EntityRef<Employee> _Employee1;
		
		private EntityRef<Course_status> _Course_status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onclient_phoneChanging(string value);
    partial void Onclient_phoneChanged();
    partial void Ondepositor_idChanging(System.Nullable<int> value);
    partial void Ondepositor_idChanged();
    partial void Ontaxidriver_idChanging(System.Nullable<int> value);
    partial void Ontaxidriver_idChanged();
    partial void OndateChanging(System.DateTime value);
    partial void OndateChanged();
    partial void Onstartpoint_nameChanging(string value);
    partial void Onstartpoint_nameChanged();
    partial void Onstartpoint_latChanging(decimal value);
    partial void Onstartpoint_latChanged();
    partial void Onstartpoint_lonChanging(decimal value);
    partial void Onstartpoint_lonChanged();
    partial void Onendpoint_latChanging(decimal value);
    partial void Onendpoint_latChanged();
    partial void Onendpoint_lonChanging(decimal value);
    partial void Onendpoint_lonChanged();
    partial void Oncourse_status_idChanging(System.Nullable<int> value);
    partial void Oncourse_status_idChanged();
    partial void Oncourse_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncourse_dateChanged();
    partial void Onclient_nameChanging(string value);
    partial void Onclient_nameChanged();
    partial void OnseatsChanging(System.Nullable<int> value);
    partial void OnseatsChanged();
    partial void Oncar_type_idChanging(System.Nullable<int> value);
    partial void Oncar_type_idChanged();
    #endregion
		
		public Course()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_phone", DbType="VarChar(15)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string client_phone
		{
			get
			{
				return this._client_phone;
			}
			set
			{
				if ((this._client_phone != value))
				{
					this.Onclient_phoneChanging(value);
					this.SendPropertyChanging();
					this._client_phone = value;
					this.SendPropertyChanged("client_phone");
					this.Onclient_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="rep_id", Storage="_depositor_id", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<int> depositor_id
		{
			get
			{
				return this._depositor_id;
			}
			set
			{
				if ((this._depositor_id != value))
				{
					this.Ondepositor_idChanging(value);
					this.SendPropertyChanging();
					this._depositor_id = value;
					this.SendPropertyChanged("depositor_id");
					this.Ondepositor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="taxi_id", Storage="_taxidriver_id", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.Nullable<int> taxidriver_id
		{
			get
			{
				return this._taxidriver_id;
			}
			set
			{
				if ((this._taxidriver_id != value))
				{
					this.Ontaxidriver_idChanging(value);
					this.SendPropertyChanging();
					this._taxidriver_id = value;
					this.SendPropertyChanged("taxidriver_id");
					this.Ontaxidriver_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startpoint_name", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string startpoint_name
		{
			get
			{
				return this._startpoint_name;
			}
			set
			{
				if ((this._startpoint_name != value))
				{
					this.Onstartpoint_nameChanging(value);
					this.SendPropertyChanging();
					this._startpoint_name = value;
					this.SendPropertyChanged("startpoint_name");
					this.Onstartpoint_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startpoint_lat", DbType="Decimal(11,7) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public decimal startpoint_lat
		{
			get
			{
				return this._startpoint_lat;
			}
			set
			{
				if ((this._startpoint_lat != value))
				{
					this.Onstartpoint_latChanging(value);
					this.SendPropertyChanging();
					this._startpoint_lat = value;
					this.SendPropertyChanged("startpoint_lat");
					this.Onstartpoint_latChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startpoint_lon", DbType="Decimal(11,7) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public decimal startpoint_lon
		{
			get
			{
				return this._startpoint_lon;
			}
			set
			{
				if ((this._startpoint_lon != value))
				{
					this.Onstartpoint_lonChanging(value);
					this.SendPropertyChanging();
					this._startpoint_lon = value;
					this.SendPropertyChanged("startpoint_lon");
					this.Onstartpoint_lonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endpoint_lat", DbType="Decimal(11,7) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public decimal endpoint_lat
		{
			get
			{
				return this._endpoint_lat;
			}
			set
			{
				if ((this._endpoint_lat != value))
				{
					this.Onendpoint_latChanging(value);
					this.SendPropertyChanging();
					this._endpoint_lat = value;
					this.SendPropertyChanged("endpoint_lat");
					this.Onendpoint_latChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endpoint_lon", DbType="Decimal(11,7) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public decimal endpoint_lon
		{
			get
			{
				return this._endpoint_lon;
			}
			set
			{
				if ((this._endpoint_lon != value))
				{
					this.Onendpoint_lonChanging(value);
					this.SendPropertyChanging();
					this._endpoint_lon = value;
					this.SendPropertyChanged("endpoint_lon");
					this.Onendpoint_lonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_status_id", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public System.Nullable<int> course_status_id
		{
			get
			{
				return this._course_status_id;
			}
			set
			{
				if ((this._course_status_id != value))
				{
					if (this._Course_status.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncourse_status_idChanging(value);
					this.SendPropertyChanging();
					this._course_status_id = value;
					this.SendPropertyChanged("course_status_id");
					this.Oncourse_status_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_date", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public System.Nullable<System.DateTime> course_date
		{
			get
			{
				return this._course_date;
			}
			set
			{
				if ((this._course_date != value))
				{
					this.Oncourse_dateChanging(value);
					this.SendPropertyChanging();
					this._course_date = value;
					this.SendPropertyChanged("course_date");
					this.Oncourse_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_name", DbType="VarChar(150)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public string client_name
		{
			get
			{
				return this._client_name;
			}
			set
			{
				if ((this._client_name != value))
				{
					this.Onclient_nameChanging(value);
					this.SendPropertyChanging();
					this._client_name = value;
					this.SendPropertyChanged("client_name");
					this.Onclient_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seats", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public System.Nullable<int> seats
		{
			get
			{
				return this._seats;
			}
			set
			{
				if ((this._seats != value))
				{
					this.OnseatsChanging(value);
					this.SendPropertyChanging();
					this._seats = value;
					this.SendPropertyChanged("seats");
					this.OnseatsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_type_id", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15)]
		public System.Nullable<int> car_type_id
		{
			get
			{
				return this._car_type_id;
			}
			set
			{
				if ((this._car_type_id != value))
				{
					if (this._Car_type.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncar_type_idChanging(value);
					this.SendPropertyChanging();
					this._car_type_id = value;
					this.SendPropertyChanged("car_type_id");
					this.Oncar_type_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Car_type_Course", Storage="_Car_type", ThisKey="car_type_id", OtherKey="id", IsForeignKey=true)]
		public Car_type Car_type
		{
			get
			{
				return this._Car_type.Entity;
			}
			set
			{
				Car_type previousValue = this._Car_type.Entity;
				if (((previousValue != value) 
							|| (this._Car_type.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Car_type.Entity = null;
						previousValue.Courses.Remove(this);
					}
					this._Car_type.Entity = value;
					if ((value != null))
					{
						value.Courses.Add(this);
						this._car_type_id = value.id;
					}
					else
					{
						this._car_type_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Car_type");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employee_Course", Storage="_Employee", ThisKey="depositor_id", OtherKey="id", IsForeignKey=true)]
		public Employee Employee
		{
			get
			{
				return this._Employee.Entity;
			}
			set
			{
				Employee previousValue = this._Employee.Entity;
				if (((previousValue != value) 
							|| (this._Employee.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Employee.Entity = null;
						previousValue.Courses.Remove(this);
					}
					this._Employee.Entity = value;
					if ((value != null))
					{
						value.Courses.Add(this);
						this._depositor_id = value.id;
					}
					else
					{
						this._depositor_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Employee");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employee_Course1", Storage="_Employee1", ThisKey="taxidriver_id", OtherKey="id", IsForeignKey=true)]
		public Employee Employee1
		{
			get
			{
				return this._Employee1.Entity;
			}
			set
			{
				Employee previousValue = this._Employee1.Entity;
				if (((previousValue != value) 
							|| (this._Employee1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Employee1.Entity = null;
						previousValue.Courses1.Remove(this);
					}
					this._Employee1.Entity = value;
					if ((value != null))
					{
						value.Courses1.Add(this);
						this._taxidriver_id = value.id;
					}
					else
					{
						this._taxidriver_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Employee1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Course_status_Course", Storage="_Course_status", ThisKey="course_status_id", OtherKey="id", IsForeignKey=true)]
		public Course_status Course_status
		{
			get
			{
				return this._Course_status.Entity;
			}
			set
			{
				Course_status previousValue = this._Course_status.Entity;
				if (((previousValue != value) 
							|| (this._Course_status.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Course_status.Entity = null;
						previousValue.Courses.Remove(this);
					}
					this._Course_status.Entity = value;
					if ((value != null))
					{
						value.Courses.Add(this);
						this._course_status_id = value.id;
					}
					else
					{
						this._course_status_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Course_status");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			this._Car_type = default(EntityRef<Car_type>);
			this._Employee = default(EntityRef<Employee>);
			this._Employee1 = default(EntityRef<Employee>);
			this._Course_status = default(EntityRef<Course_status>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
}
#pragma warning restore 1591
